FROM golang:1.25.6-bookworm AS builder

WORKDIR /go/src/github.com/newrelic/newrelic-fluent-bit-output


COPY Makefile go.* *.go /go/src/github.com/newrelic/newrelic-fluent-bit-output/
COPY config/ /go/src/github.com/newrelic/newrelic-fluent-bit-output/config
COPY metrics/ /go/src/github.com/newrelic/newrelic-fluent-bit-output/metrics
COPY nrclient/ /go/src/github.com/newrelic/newrelic-fluent-bit-output/nrclient
COPY record/ /go/src/github.com/newrelic/newrelic-fluent-bit-output/record
COPY utils/ /go/src/github.com/newrelic/newrelic-fluent-bit-output/utils

ENV SOURCE docker

# Not using default value here due to this: https://github.com/docker/buildx/issues/510
ARG TARGETPLATFORM
ENV TARGETPLATFORM=${TARGETPLATFORM:-linux/amd64}
RUN echo "Building for ${TARGETPLATFORM} architecture"
RUN make ${TARGETPLATFORM}

    # aws-for-fluent-bit 3.2.1 is based on Fluent Bit 4.2.2: https://github.com/aws/aws-for-fluent-bit/releases/tag/v3.2.1
FROM amazon/aws-for-fluent-bit:3.2.1

# Expose this env variable so that the version can be used in the helm chart
ENV FBVERSION=4.2.2

# Fix CVE-2025-15467 (OpenSSL) - apply security update
USER root
RUN yum update -y openssl && \
    yum clean all && \
    rm -rf /var/cache/yum
USER fluent-bit

COPY --from=builder /go/src/github.com/newrelic/newrelic-fluent-bit-output/out_newrelic-linux-*.so /fluent-bit/bin/out_newrelic.so
COPY *.conf /fluent-bit/etc/

CMD ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf", "-e", "/fluent-bit/bin/out_newrelic.so"]
