on: [pull_request]
  #issues:
  #  types: [opened]

name: Test Creating issue

jobs:
  test-creating-issue:
    name: Create Ticket for new Issue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: LOGGING
          issuetype: Task
          summary: |
            [${{ github.repository }}] ISSUE #issue.number
          description: |
            Please check this issue: ${{ github.event.issue.url }}
          fields: '{"labels": ["sunstone-hero"], "customfield_11700": "LOGGING-5562"}'

      - name: Log created issue
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"