name: New Relic Fluent Bit Output Plugin - Merge to master

on:
  push:
    branches:
      - master

jobs:
  cd:
    name: Continuous Delivery pipeline
    runs-on: ubuntu-24.04

    steps:
      - name: Set up Go 1.25.8
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # git ls-remote https://github.com/actions/setup-go v5
        with:
          go-version: '1.25.8'

      - name: Check go version
        run: go version

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #git ls-remote https://github.com/actions/checkout v4.2.2

      - name: Run unit tests
        run: go test ./...

      - name: Determine new plugin version
        run: |
          set -euo pipefail
          VERSION=$(cat version.go | grep VERSION | awk '{gsub(/"/, "", $4); print $4}')
          echo "Determined version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV       
      
      - name: Set up Zig
        uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # git ls-remote https://github.com/mlugg/setup-zig v2
        with:
          version: 0.13.0

      - name: Build All Binaries (Zig)
        run: |
          chmod +x .github/scripts/build_ohai.sh
          .github/scripts/build_ohai.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # git ls-remote https://github.com/docker/setup-qemu-action v3.2.0

      # The Docker Buildx builder will be used later to leverage from the cache while building the image
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # git ls-remote https://github.com/docker/setup-buildx-action v3.8.0

      # Cache to be used by Docker Buildx
      - name: Set up Docker Buildx's cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # git ls-remote https://github.com/actions/cache v4.2.0
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # git ls-remote https://github.com/docker/login-action v3.3.0
        with:
          username: ${{ secrets.SVC_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.SVC_DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Publish Docker image
        if: ${{ !contains(env.VERSION, 'beta') }}
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # git ls-remote https://github.com/docker/build-push-action v6
        env:
          DOCKERHUB_REPOSITORY: newrelic/newrelic-fluentbit-output
          IMAGE_TAG: ${{ env.VERSION }}
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPOSITORY }}:latest
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.IMAGE_TAG }}
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build and Publish Docker beta image
        if: ${{ contains(env.VERSION, 'beta') }}
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # git ls-remote https://github.com/docker/build-push-action v6
        env:
          DOCKERHUB_REPOSITORY: newrelic/newrelic-fluentbit-output
          IMAGE_TAG: ${{ env.VERSION }}
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.IMAGE_TAG }}
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          
      - name: Inspect published Docker image
        run: docker buildx imagetools inspect newrelic/newrelic-fluentbit-output:${{ env.VERSION }}

      - name: Build and Publish Docker debug image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # git ls-remote https://github.com/docker/build-push-action v6
        env:
          DOCKERHUB_REPOSITORY: newrelic/newrelic-fluentbit-output
          IMAGE_TAG: ${{ env.VERSION }}-debug
        with:
          context: ./
          file: ./Dockerfile_debug
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.IMAGE_TAG }}
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64, linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Inspect published Docker debug image
        run: docker buildx imagetools inspect newrelic/newrelic-fluentbit-output:${{ env.VERSION }}-debug

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@5579c002bb4778aa43395ef1df492868a9a1c83f # git ls-remote https://github.com/aws-actions/configure-aws-credentials v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@4625ce35226a7557230889aae2f52eb50ec3dcda # git ls-remote https://github.com/aws-actions/amazon-ecr-login v2.0.1

      - name: Build and Publish Docker image for Firelens
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # git ls-remote https://github.com/docker/build-push-action v6
        env:
          ECR_REGISTRY: 533243300146.dkr.ecr.us-east-2.amazonaws.com
          ECR_REPOSITORY: newrelic/logging-firelens-fluentbit
          IMAGE_TAG: ${{ env.VERSION }}
        with:
          context: ./
          file: ./Dockerfile_firelens
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          builder: ${{ steps.buildx.outputs.name }}
          # Firelens image only available for amd64 and arm64 architectures
          platforms: linux/amd64, linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Inspect published Docker Firelens image
        run: docker buildx imagetools inspect 533243300146.dkr.ecr.us-east-2.amazonaws.com/newrelic/logging-firelens-fluentbit:${{ env.VERSION }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e #git ls-remote https://github.com/actions/create-release v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: newrelic-fluent-bit-output-${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Include linux-amd64 artifact in release
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # git ls-remote https://github.com/actions/upload-release-asset v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out_newrelic-linux-amd64-${{ env.VERSION }}.so
          asset_name: out_newrelic-linux-amd64-${{ env.VERSION }}.so
          asset_content_type: application/octet-stream

      - name: Include windows-amd64 artifact in release
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # git ls-remote https://github.com/actions/upload-release-asset v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out_newrelic-windows-amd64-${{ env.VERSION }}.dll
          asset_name: out_newrelic-windows-amd64-${{ env.VERSION }}.dll
          asset_content_type: application/octet-stream

      - name: Include windows-386 artifact in release
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # git ls-remote https://github.com/actions/upload-release-asset v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out_newrelic-windows-386-${{ env.VERSION }}.dll
          asset_name: out_newrelic-windows-386-${{ env.VERSION }}.dll
          asset_content_type: application/octet-stream

      - name: Include linux-arm64 artifact in release
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # git ls-remote https://github.com/actions/upload-release-asset v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out_newrelic-linux-arm64-${{ env.VERSION }}.so
          asset_name: out_newrelic-linux-arm64-${{ env.VERSION }}.so
          asset_content_type: application/octet-stream

      - name: Include linux-arm artifact in release
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # git ls-remote https://github.com/actions/upload-release-asset v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out_newrelic-linux-arm-${{ env.VERSION }}.so
          asset_name: out_newrelic-linux-arm-${{ env.VERSION }}.so
          asset_content_type: application/octet-stream

  windows-docker-images:
    name:  ${{ matrix.name }} Docker image generation and publishing
    # We aim to support https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#windows-os-version-support
    # More info: https://cloud.google.com/kubernetes-engine/docs/how-to/creating-a-cluster-windows#choose_your_windows_server_node_image
    # Tag reference: https://hub.docker.com/_/microsoft-windows-servercore
    # Compatibility matrix: https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility
    strategy:
      matrix:
        include:
#          - name: Windows Server 2019 (LTSC)
#            windowsVersion: 2019
#            windowsImageTag: ltsc2019-amd64
#            imageTagSuffix: windows-ltsc-2019
#            # Uses self-hosted runner which has Hyper-V virtualization support, since windows-2019 GH runner was deprecated
#            runsOn: windows-x64-8-core
#            # More info on isolation: https://learn.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/hyperv-container
#            isolation: hyperv
          - name: Windows Server 2022 (LTSC)
            windowsVersion: 2022
            windowsImageTag: ltsc2022-amd64
            imageTagSuffix: windows-ltsc-2022
            runsOn: windows-2022
            isolation: process

    runs-on: ${{ matrix.runsOn }}

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #git ls-remote https://github.com/actions/checkout v4.2.2

      - name: Determine new plugin version
        run: |
          $env:VERSION=(Select-String -Path version.go -Pattern 'const VERSION = "(.*)"').Matches.Groups[1].Value
          echo "Determined version: $env:VERSION"
          # After the following command, the VERSION variable is available via the "env" command in the GH action
          Add-Content -Path $env:GITHUB_ENV -Value "VERSION=$env:VERSION"

      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 #git ls-remote https://github.com/docker/login-action v3.3.0
        with:
          username: ${{ secrets.SVC_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.SVC_DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Publish Docker image for ${{ matrix.name }}
        env:
          DOCKERHUB_REPOSITORY: newrelic/newrelic-fluentbit-output
          IMAGE_TAG: ${{ env.VERSION }}-${{ matrix.imageTagSuffix }}
        run: |
          docker build --platform windows/amd64 --isolation=${{ matrix.isolation }} -f Dockerfile.windows -t ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.IMAGE_TAG }} --build-arg WINDOWS_VERSION=${{ matrix.windowsVersion }} .
          docker push ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.IMAGE_TAG }}

  windows-docker-images-older-version:
    name:  ${{ matrix.name }} Docker image generation and publishing
    # Windows 2019 needs to run older version of fluent bit as base images are not being published after fluent bit 4.0.3
    # We aim to support https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#windows-os-version-support
    # More info: https://cloud.google.com/kubernetes-engine/docs/how-to/creating-a-cluster-windows#choose_your_windows_server_node_image
    # Tag reference: https://hub.docker.com/_/microsoft-windows-servercore
    # Compatibility matrix: https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility
    strategy:
      matrix:
        include:
          - name: Windows Server 2019 (LTSC)
            windowsVersion: 2019
            windowsImageTag: ltsc2019-amd64
            imageTagSuffix: windows-ltsc-2019
            # Uses self-hosted runner which has Hyper-V virtualization support, since windows-2019 GH runner was deprecated
            runsOn: windows-x64-8-core
            # More info on isolation: https://learn.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/hyperv-container
            isolation: hyperv

    runs-on: ${{ matrix.runsOn }}

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #git ls-remote https://github.com/actions/checkout v4.2.2

      - name: Determine new plugin version
        run: |
          $env:VERSION=(Select-String -Path version.go -Pattern 'const VERSION = "(.*)"').Matches.Groups[1].Value
          echo "Determined version: $env:VERSION"
          # After the following command, the VERSION variable is available via the "env" command in the GH action
          Add-Content -Path $env:GITHUB_ENV -Value "VERSION=$env:VERSION"

      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 #git ls-remote https://github.com/docker/login-action v3.3.0
        with:
          username: ${{ secrets.SVC_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.SVC_DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Publish Docker image for ${{ matrix.name }}
        env:
          DOCKERHUB_REPOSITORY: newrelic/newrelic-fluentbit-output
          IMAGE_TAG: ${{ env.VERSION }}-${{ matrix.imageTagSuffix }}
        run: |
          docker build --platform windows/amd64 --isolation=${{ matrix.isolation }} -f Dockerfile.windows_older -t ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.IMAGE_TAG }} --build-arg WINDOWS_VERSION=${{ matrix.windowsVersion }} .
          docker push ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.IMAGE_TAG }}